### ISSUE TITLE
changing menu itmes

### ISSUE THREAD

**Issue by hebaeldeek** [dualcube/moodle-theme_roshnilite#11]
hello,

Thank you for your great theme, i have downloaded it from moodle.org, i have a problem add my moodle menu i have tried to add it from the theme settings and it dose n`t work, kindly clarify the way to modify the menu items.

thank you

**Comment by parthajeet** [comment]
Hello,

Thanks for the appreciating words. We have updated our theme to support the default Moodle menu from the Moodle theme settings page. Now you can download the latest version from Moodle.org.

Regards,
Parthajeet~

**Comment by hebaeldeek** [comment]
Hello, Parthajeet

Kindly note that i have downloaded the theme from moodle.org two weeks ago, did you upgrade it after that or not?

**Comment by parthajeet** [comment]
Hello,

Yes. We have uploaded it yesterday. So you can download the latest version.

Thanks,
Parthajeet~

**Comment by ghost** [comment]
Hello,

Again, thank you for your great theme. I have the same problem. I'm using the lastest version of the theme (Release date: sábado, 30 de julio de 2016, 15:29), but I don't see these elements in the menu:

Grades.
Messages.
Preferences.

Kindly can you help me (I'm sorry for my english. I'm learning to speak english yet).

**Comment by parthajeet** [comment]
Hello,

Thanks for the appreciation. We have updated the theme with default Moodle user menu. Now you can download the latest version from Moodle.org.

Regards,
Parthajeet~
