### ISSUE TITLE
Call to undefined method theme_roshnilite_core_renderer::navbar_plugin_output()

### ISSUE THREAD

**Issue by stelehm** [dualcube/moodle-theme_roshnilite#16]
Hello,

we just loaded the newest update of your theme and suddenly this error-message appeared: 
![image](https://cloud.githubusercontent.com/assets/5700597/23719699/b0827e84-043c-11e7-8070-907e7e39764a.png)

Is this a known issue, if yes, what can we do to fix it?
It makes our installation completely unusable.

Thank you for your help and with kind regards,
SteLehm

**Comment by parthajeet** [comment]
Hello,

We have updated the plugin. Kindly download the latest zip from moodle.org.

Regards,
Parthajeet~
