### ISSUE TITLE
The images of the courses do not appear

### ISSUE THREAD

**Issue by cdaty** [dualcube/moodle-theme_roshnilite#18]
Hello the images of the courses do not appear and are doubling the name of the courses, how can I solve the problem?
![foto de cursos](https://cloud.githubusercontent.com/assets/27737120/25144972/5745c948-2435-11e7-840a-18e741cca9b3.jpg)

**Comment by parthajeet** [comment]
Hello,

Can you once try deleting the images from course settings then add them again. Else please provide us the url and admin access of your site so that we can debug.

Thanks,
Parthajeet~

**Comment by cdaty** [comment]
ok, https://cdaty.milaulas.com/ 

Username: admin
Password: ReAc@823

**Comment by parthajeet** [comment]
As of now we have checked that the images are showing correctly in your site.  Regarding the doubling of courses - the slider repeats the courses after all the courses are displayed in the view port.

Regards,
Parthajeet~
