### ISSUE TITLE
Moodle book and (un)ordered list

### ISSUE THREAD

**Issue by jannedermeijer** [dualcube/moodle-theme_roshnilite#19]
When I try to make an enumeration with numbers or dots. The symbol appears above the sentence. I cannot change this. Also, copy-paste summeries from Word gives this problem
It should look like this:
The enumeration in other moodle activities are working normally. But not in this 'issue'.
Regards Jan

**Comment by parthajeet** [comment]
Hello, 

We have fixed the issue. You can download the latest zip from Moodle.org.

Regards,
Parthajeet~

**Comment by jannedermeijer** [comment]
I think I downloaded de zip-file correctly. But the enumeration when maken chapters/subchapters in the moodle book are not working correctly.

**Comment by parthajeet** [comment]
Can you once purge all caches from the below site map

site admin -> development - purge all caches.

If the issue still exists then you can provide us your site access details so that we can debug.

Regards,
Parthajeet~

**Comment by jannedermeijer** [comment]
http://moodle.curriculumdesignhe.eu/, click Blended learning and MHE Blended learning: Admin and FoxBetA31469*

I can use the enumeration in the moodle book. However, you can’t see the numbers of the dots it in the presentation. Also, if you want to correct the enumeration appears above the sentence instead before the sentence.
Regards Jan

Jan Nedermeijer, MSc
Coebelweg 4, 2324KW Leiden
+31613705442
Skypenaam jannedermeijer
http://www.lde-studentsuccess.com
http://bl.curriculumdesignhe.eu<http://bl.curriculumdesignhe.eu/>
PUM Netherlands Senior Experts

Van: parthajeet [mailto:notifications@github.com]
Verzonden: vrijdag 7 juli 2017 15:12
Aan: dualcube/moodle-theme_roshnilite <moodle-theme_roshnilite@noreply.github.com>
CC: jannedermeijer <jannedermeijer@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [dualcube/moodle-theme_roshnilite] Moodle book and (un)ordered list (#19)


Can you once purge all caches from the below site map

site admin -> development - purge all caches.

If the issue still exists then you can provide us your site access details so that we can debug.

Regards,
Parthajeet~

**Comment by jannedermeijer** [comment]
http://moodle.curriculumdesignhe.eu/, click Blended learning and MHE Blended learning: Admin and FoxBetA31469*

I can use the enumeration in the moodle book. However, you can’t see the numbers of the dots it in the presentation. Also, if you want to correcta sentence  the enumeration appears above the sentence instead before the sentence.
There are two examples of a Moodle book in the coourse
Regards Jan

**Comment by parthajeet** [comment]
Hello,

Thanks for the login details, we are checking and will update you shortly.

Regards,
Parthajeet~

**Comment by parthajeet** [comment]
Hello,

The Roshni lite theme in your Moodle installation is not the updated one. We have added the css in Roshni lite custom css settings as of now to fix the issue. Kindly download the latest zip from Moodle.org.

Regards,
Parthajeet~

**Comment by jannedermeijer** [comment]
Thank you, its now working.
Jan

**Comment by parthajeet** [comment]
Thanks.
Parthajeet~
