### ISSUE TITLE
Excepción - Call to a member function getAttribute() on null

### ISSUE THREAD

**Issue by jacpepe** [dualcube/moodle-theme_roshnilite#20]
This error appear when a try to add an user under ADMINISTRACION --> Usuarios --> Cuentas --> Agregar un usuario (ADMINISTRATION --> Users --> Accounts --> Add user)

**Comment by parthajeet** [comment]
Hello,

Can you please turn on the debugging and then provide us a screenshot. As we have checked in our site and we are not getting this error.

Regards,
Parthajeet~
