### ISSUE TITLE
Frontpage login form causes invalid login token

### ISSUE THREAD

**Issue by Connor-Overt** [dualcube/moodle-theme_roshnilite#22]
Moodle version: 3.5.4
Plugin version: 2.5 (Build: 2014082901) (2015092116)
Issue: Front page login form causes invalid login token error and cause error "invalid login, please try again". After redirect to normal login page (/login/index.php) you can use same credentials to login correctly.

Workaround is to set Moodle config variable: 

$CFG->disablelogintoken = true;

However, this is a security risk when set.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
