### ISSUE TITLE
Compatibility with Moodle 3.7.1 ?

### ISSUE THREAD

**Issue by tikok974** [dualcube/moodle-theme_roshnilite#23]
Hi,
I tried to update my Moodle instance from version 3.6.5 to version 3.7.1 but this cannot be done because of a dependency problem with the Roshnilite theme (see log below):

```
root@mylms:/var/www/moodle# sudo -u www-data /usr/bin/php admin/cli/upgrade.php
Checking plugin dependencies failed for theme_roshnilite
All necessary plugin requirements must be met before installing this version of Moodle!

root@mylms:/var/www/moodle#
```
**Is a theme update planned to support this latest version of Moodle ?** 
Many thanks

**Comment by sumandualcube** [comment]
@tikok974 
Can you please share any recording of the issue? It worked fine when using the latest version of the theme.

Thank you.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
