### ISSUE TITLE
upload field loads indefinitely

### ISSUE THREAD

**Issue by sumandualcube** [dualcube/moodle-theme_roshnilite#24]
The upload box in the settings loads indefinitely but if I use the drag and drop options, there is no issue.

**Comment by shatarupaMsarkar** [comment]
Upload box has no problem. 
https://www.loom.com/share/0e7b2c786fe747d8b883f51e1213103c

**Comment by sumandualcube** [comment]
The problem is found on https://moodle.bitts.ca/, https://moodle.queenswoodschool.com/
recorded issue: https://drive.google.com/file/d/182IhFm7LwfDjfxYBpUFHNenUmMXlRAaB/view

**Comment by shatarupaMsarkar** [comment]
In https://moodle.queenswoodschool.com/ change the theme and try to upload a file by upload box and these also same problem found.
https://www.loom.com/share/cc16189798734461b270463b54ed004b
