### ISSUE TITLE
logged in user section on the nav bar

### ISSUE THREAD

**Issue by sumandualcube** [dualcube/moodle-theme_roshnilite#26]
logged in user section on Navbar breaks if I increase the font size.

**Comment by sumandualcube** [comment]
issue site: https://moodle.queenswoodschool.com/
recording: https://drive.google.com/file/d/1YCPF2xmtdcivpo1wK1z-TD48ve_KBlq9/view
It also shows the square logo problem.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
