### ISSUE TITLE
block breaks the site when dragged

### ISSUE THREAD

**Issue by sumandualcube** [dualcube/moodle-theme_roshnilite#27]
When a new block is added to the left menu section, it works alright but if I try to drag it to the right block section, the page breaks.

**Comment by shatarupaMsarkar** [comment]
This problem also can't be found in our server or my local machine.
https://www.loom.com/share/daacc88dd6af47359db6550ea1b60329

**Comment by sumandualcube** [comment]
Problem detected on https://moodle.bitts.ca/

regeneration: https://drive.google.com/file/d/1iEoR4YsjUvB3zCoySRWAXC5mSBlNcENC/view

**Comment by kndnsow** [comment]
it's solved and added in the latest version
tips: drag the block only for up-down move, if want to change side use [Configure block] option
