### ISSUE TITLE
Can't use Moodle site at all after activating the Roshnilite Moodle theme

### ISSUE THREAD

**Issue by michael-milette** [dualcube/moodle-theme_roshnilite#3]
I just downloaded and installed the latest version of the theme 2.5 (Build: 2014082901) available on Moodle.org. As soon as I activate the theme, I get the following error:

Fatal error: Can't use method return value in write context in /var/www/moodle/theme/roshnilite/classes/core_renderer.php on line 56

It is installed on Moodle 2.7.10 with PHP 5.4.4

Best regards,

Michael

**Comment by parthajeet** [comment]
Hello Michael,

We have fixed the issue. You can now download the latest theme zip from moodle.org. Let us know if you face any issue.

Thanks,
parthaJeet~

**Comment by michael-milette** [comment]
Thanks! I am now able to view the site.
