### ISSUE TITLE
Large amount of white space on site

### ISSUE THREAD

**Issue by gleckert** [dualcube/moodle-theme_roshnilite#31]
There is a large amount of white space on either side of the columns.  The center column (or all coulmns) I would think should resize to screen size.  The attached picture is at 1920x1080 resolution.  Screenshot attached.
![whitespace](https://user-images.githubusercontent.com/69544591/89953333-b93c0900-dbe3-11ea-8b80-be2c349187ff.jpg)

**Comment by moumitahalder** [comment]
Hi @gleckert , we have released an update with the latest moodle version support and added the fix. Kindly update the theme and check.
