### ISSUE TITLE
3.2 Not Compatible with 3.X Moodle

### ISSUE THREAD

**Issue by WKupper** [dualcube/moodle-theme_roshnilite#35]
$plugin->dependencies = array('theme_boost' => 2022041900);

In version.php means this will only work with the latest 4.x moodles

Boost theme on 3.x is way older. 

Should update versions page for which moodle versions are supported.

**Comment by moumitahalder** [comment]
Hi @WKupper , we have released an update with the latest moodle version support. Kindly update the theme and check.
