### ISSUE TITLE
Front page images don't appear when logged out

### ISSUE THREAD

**Issue by michael-milette** [dualcube/moodle-theme_roshnilite#4]
On the front page, images don't appear when I am logged out. For example:

![image](https://cloud.githubusercontent.com/assets/3808579/10929826/64ca2d90-8286-11e5-9b6f-0d9f6340339e.png)

The images in each case were uploaded by dragging and dropping them into the appropriate theme settings fields during the installation of the theme.

When I view the source code, I see links that look like this:

<img alt="" src="//example.com/moodle/pluginfile.php/1/theme_roshnilite/aboutsiteimage1/1446612567/image-1.jpg">

Best regards,

Michael

**Comment by michael-milette** [comment]
The View All Courses section of the front page looks like this. Nothing ever appears and the animation just keeps going around in circles:

![image](https://cloud.githubusercontent.com/assets/3808579/10929897/1a09c576-8287-11e5-892e-f8e431b286b1.png)

**Comment by parthajeet** [comment]
Thanks for pointing out, this is fixed now.

Regards,
parthaJeet~
