### ISSUE TITLE
Issue with 4.2 moodle version course section

### ISSUE THREAD

**Issue by BauerPablo** [dualcube/moodle-theme_roshnilite#47]
Trazado de la pila (stack):
line 104 of /lib/weblib.php: TypeError thrown
line 104 of /lib/weblib.php: call to htmlspecialchars()
line 32 of /.htyafbfakweesm.data/localcache/mustache/-1/roshnilite/__Mustache_a3d87a9e8dbdfebc2971be0d53490c77.php: call to s()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_a3d87a9e8dbdfebc2971be0d53490c77->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 2171 of /lib/outputrenderers.php: call to renderer_base->render_from_template()
line 54 of /theme/boost/classes/output/core_renderer.php: call to core_renderer->render_single_button()
line 258 of /course/view.php: call to theme_boost\output\core_renderer->edit_button()

**Comment by kndnsow** [comment]
resolved in last update version 3.5.1
