### ISSUE TITLE
A link to Site Blog appears on Front Page even though Blogging is Disabled

### ISSUE THREAD

**Issue by michael-milette** [dualcube/moodle-theme_roshnilite#5]
Blogging is disabled on my site however a _Site Blog_ the button still appears in the top navigation. When I click it, I see the following error message:

![image](https://cloud.githubusercontent.com/assets/3808579/10929951/9633dde4-8287-11e5-842a-67a8836a18ba.png)

Best regards,

Michael

**Comment by parthajeet** [comment]
Thanks for pointing out, this is fixed now.

Regards,
parthaJeet~
