### ISSUE TITLE
Question - Are you guys taking suggestions?

### ISSUE THREAD

**Issue by tadeucaldas** [dualcube/moodle-theme_roshnilite#54]
I´ll be using roshni lite as my "to go" theme from now on... are you guys open for suggestions? I´m asking to know if i can open issues about things some users migth want and make the theme even more competitive.

**Comment by moumitahalder** [comment]
Thank you for considering Roshni Lite as your preferred theme! 

Yes, absolutely! We're always open to suggestions and feedback from our users. Your input is invaluable to us as it helps us improve the theme. You can contact us over our mail admin@dualcube.com

Also, We specialize in Moodle customization and development. If you require assistance with Moodle modifications, feel free to reach out to us via email as well.

Looking forward to hearing your suggestions!
