### ISSUE TITLE
Login Form on Front Page causes download of backup.mbz

### ISSUE THREAD

**Issue by michael-milette** [dualcube/moodle-theme_roshnilite#6]
When I try to login using the form in the header of the Front Page, instead of logging in, the site initiates a download of a file called backup.mbz. Using 7zip to open the file, It looks like a backup of a course. What I expected was to login to the site.

Here is a screenshot of the contents of backup.mbz:

![image](https://cloud.githubusercontent.com/assets/3808579/10930022/7ab99954-8288-11e5-8935-667c3539c1b5.png)

This is on Moodle 2.7.10+.

Best regards,

Michael

**Comment by parthajeet** [comment]
Is there any backup related cron running in background. Because we couldn't replicate any such issues in other Moodle environment.

**Comment by michael-milette** [comment]
There are no backup processes running at all. I have over 30 themes installed on my site and this is the only one that is doing this.

Using the latest version that I downloaded today, I did manage to login once successfully. I had been logged in with another theme, then logged out and then back in again. However, when I then logged out and back in again, it was back to downloading backup.mbz.

By the way, when this happens, I can then click on a link on the page and I discover that I am logged in.

The same thing happens in Chrome, Firefox and Internet Explorer.

**Comment by parthajeet** [comment]
Can you please share your server access and Moodle admin login details with us? So that we can check.

**Comment by michael-milette** [comment]
Sorry, I can't do that.

**Comment by parthajeet** [comment]
Hi,

We have tried for a considerable number of environments and with the last version of our theme, we couldn't find this issue in any one if them. Hence, we are not considering it as bug unless any other also point this same issue. i hope you will understand.

**Comment by Jorgiux83** [comment]
i've the same problem, when im loggin, start download last backup

**Comment by kndnsow** [comment]
it's solved and added in the latest version
