### ISSUE TITLE
Navigation dots for content slider on Front page appear over some of the text

### ISSUE THREAD

**Issue by michael-milette** [dualcube/moodle-theme_roshnilite#7]
On my front page, I added three slides. Using the default text that comes with the theme, I noticed that the dots appear right over some of the text. Take a look:

![image](https://cloud.githubusercontent.com/assets/3808579/10930054/d75271ae-8288-11e5-91a8-2d1472979a39.png)

Best regards,

Michael

**Comment by parthajeet** [comment]
Thanks for pointing out, this is fixed now.

Regards,
parthaJeet~

**Comment by michael-milette** [comment]
I just installed the theme again and this does not appear to be fixed. Is the fix available from somewhere?

**Comment by parthajeet** [comment]
Kindly download the latest theme zip from moodle.org. It is also fixed in our github version.

**Comment by michael-milette** [comment]
Looks to me like your last update was on November 6. That is the version I have installed.

**Comment by parthajeet** [comment]
Hi,

We have tried for a considerable number of environments and with the last version of our theme, we couldn't find this issue in any one if them. Hence, we are not considering it as bug unless any other also point this same issue. i hope you will understand.
