### ISSUE TITLE
Front page Moodle content does not appear to be lined up with the rest of the content

### ISSUE THREAD

**Issue by michael-milette** [dualcube/moodle-theme_roshnilite#8]
I added "Available Courses" to my front page in the Front page settings. However, when viewing the front page (logged out), the section does not seem to be lined up with the rest of the content above it on the page.

Best regards,

Michael

**Comment by parthajeet** [comment]
Thanks for pointing out, this is fixed now.

Regards,
parthaJeet~

**Comment by michael-milette** [comment]
I just installed the theme again and this does not appear to be fixed. Is the fix available from somewhere?

**Comment by parthajeet** [comment]
Kindly download the latest theme zip from moodle.org. It is also fixed in our github version.
